-- AlterEnum
ALTER TYPE "PointReason" ADD VALUE 'PURCHASE_REVERSED';

-- AlterTable
ALTER TABLE "MarketingSetting" ADD COLUMN     "earnMultiplierBp" INTEGER NOT NULL DEFAULT 10000,
ADD COLUMN     "earnRateBp" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "loyaltyEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "minRedeemPoints" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "multiplierUntil" TIMESTAMP(3),
ADD COLUMN     "redeemMaxBp" INTEGER NOT NULL DEFAULT 2000;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "pointsPaisa" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pointsUsed" INTEGER NOT NULL DEFAULT 0;
